name: CD - Deploy to AWS

on:
  workflow_run:
    workflows: ["CI - Build and Push"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to AWS via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ubuntu
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            mkdir -p ~/ci-cd-app
            cd ~/ci-cd-app
            
            # Create Nginx Config for Reverse Proxy
            cat <<EOF > nginx.conf
            server {
                listen 80;
                
                location / {
                    root /usr/share/nginx/html;
                    index index.html;
                    try_files \$uri \$uri/ /index.html;
                }

                location /api/ {
                    proxy_pass http://backend:4000;
                    proxy_http_version 1.1;
                    proxy_set_header Upgrade \$http_upgrade;
                    proxy_set_header Connection 'upgrade';
                    proxy_set_header Host \$host;
                    proxy_cache_bypass \$http_upgrade;
                }
            }
            EOF

            # Create Docker Compose file
            cat <<EOF > docker-compose.yml
            services:
              backend:
                image: chandu9000/food-express-backend:latest
                environment:
                  - MONGODB_URI=mongodb+srv://Chandramohan4156:Gcm12316144@cluster0.9ujym.mongodb.net/ci-cd
                  - PORT=4000
                restart: always

              frontend:
                image: chandu9000/food-express-frontend:latest
                ports:
                  - "80:80"
                volumes:
                  - ./nginx.conf:/etc/nginx/conf.d/ default.conf:ro
                depends_on:
                  - backend
                restart: always
            EOF

            docker compose pull
            docker compose up -d
            docker image prune -f
